### ISSUE TITLE
Burp 2022.3.6 - Sharpner interferes with Burp new repeater layout

### ISSUE THREAD

**Issue by unashamedgeek** [mdsecresearch/BurpSuiteSharpener#71]
Burp 2022.3.6 made a change to repeater tabs so that rows of tabs no longer switch places when selected. With Sharpner enabled and not configured to change the Repeater interface, the rows still switch places. When Sharpner is disabled, the rows do not switch as expected based on Burp's change log.

**Comment by irsdl** [comment]
This problem was addressed since Burp changed its layout in the early adoption versions. I just opened a temporary project and added many tabs to it and it works just fine by default:
![image](https://user-images.githubusercontent.com/1798313/166260923-d971e41b-6af6-4db1-9724-ecf3597353d1.png)

It detects the burp version and tick or untick the option if the previous setting does not exist.

**Comment by irsdl** [comment]
I just gave it more testing and it seems I am saving the settings in the global settings rather than the project so I will need to fix that I think.

**Comment by unashamedgeek** [comment]
I missed that option before, thank you for showing it.

**Comment by irsdl** [comment]
This has been fixed
