### ISSUE TITLE
Scrollable Tool Pane option not applying on burp start

### ISSUE THREAD

**Issue by CrazyKidJack** [mdsecresearch/BurpSuiteSharpener#79]
**Problem:**
When starting burp, Sharpener loads and applies options properly EXCEPT for "scrollable tool pane"

-----------------------------

**Steps to reproduce:**
1. Make sure you have scrollable tool pane option selected, open a burp project, wait for Sharpener extension to load
2. Observe that:
  a. Sharpener extension loaded (for example: Burp-Tool's unique style applied correctly)
  b. Scrollable tool pane option is persisted from previous session properly (it is selected)
  c. Even though the option is selected and the extension is loaded, the option did not get applied
  d. No error messages appear in `Burp > Dashboard > Event Log` or `Burp > Extender > Extensions > Sharpener > Output/Errors`

-----------------------------

**Note:**
UNselecting and REselecting the option causes it to load for the current session... but it will fail again on the next session

**Comment by tsc-awardle** [comment]
I also noticed the issue, but only after updating to 2022.6.1

I think think I found the responsible code.  `isSubTabScrollSupportedByDefault` is set to True if Burp's version is 2022.6+, since it supports sub tab scrolling by default and I presume it conflicts with Sharpener.
https://github.com/mdsecresearch/BurpSuiteSharpener/commit/8c2a6b06fe94a5c49568064fd88815c767d3838d#diff-c54dcbc573c1def7d2f1fdbdce0ab131828698b8dc74b50d1171922142ac7be4R48-R51

This location is checking `isSubTabScrollSupportedByDefault`, and ignoring the **main** tabs if True.

https://github.com/mdsecresearch/BurpSuiteSharpener/commit/8c2a6b06fe94a5c49568064fd88815c767d3838d#diff-534c68a74e30b54d4d442785073ea5ec446223ad5196824f9fa652c5103362d1R123-R128

I think the `if (!sharedParameters.isSubTabScrollSupportedByDefault)` statement can be removed, at least until Burp adds the same scroll support for the main tabs.

I'll test and see if I can submit a PR soon.

**Comment by tsc-awardle** [comment]
Confirmed. I removed the check, rebuilt the JAR and everything works as intended.  Submitted a PR for review.

@CrazyKidJack you should be able to download my PR and run the gradle jar task if you don't want to wait for the merge.  Alternatively, rolling back to burp 2022.5.2 should also work.

Cheers!

**Comment by tsc-awardle** [comment]
![sharpener-scrollfix](https://user-images.githubusercontent.com/67977601/178067469-ebc9c544-f48e-481b-8209-e48e5b2bdb48.gif)

**Comment by irsdl** [comment]
Thanks a lot, I will have a look as soon as I get a chance :)
